

solr_record = {
 'abstract': u'abstract abstract',
 'ack': u'J.H.S. is grateful to Yujin Yang, Dennis Zaritsky, and Ann Zabludoff for their valuable comments and discussion of the results.',
 'aff': [u'Korea Astronomy and Space Science Institute, 776 Daeduk-daero, Yuseong-gu, Daejeon, 305-348, Korea',
  u'Korea Astronomy and Space Science Institute, 776 Daeduk-daero, Yuseong-gu, Daejeon, 305-348, Korea; Astronomy and Space Science Major, Korea University of Science and Technology, 217 Gajeong-ro, Yuseong-gu, Daejeon, 305-350, Korea; Department of Astrophysical Sciences, Princeton University, Princeton NJ 08544, USA'],
 'alternate_bibcode': [u'2015arXiv151103789S'],
 'arxiv_class': [u'Astrophysics - Astrophysics of Galaxies'],
 'author': [u'Shinn, Jong-Ho', u'Seon, Kwang-Il'],
 'author_count': 2,
 'author_facet': [u'Shinn, J', u'Seon, K'],
 'author_facet_hier': [u'0/Shinn, J',
  u'1/Shinn, J/Shinn, Jong-Ho',
  u'0/Seon, K',
  u'1/Seon, K/Seon, Kwang-Il'],
 'author_norm': [u'Shinn, J', u'Seon, K'],
 'bibcode': u'2015ApJ...815..133S',
 'bibstem': [u'ApJ', u'ApJ...815'],
 'bibstem_facet': u'ApJ',
 'body': u"body body",
 'citation_count': 0,
 'data': [u'CDS', u'NED'],
 'data_facet': [u'CDS', u'NED'],
 'database': [u'astronomy'],
 'date': u'2015-12-01T00:00:00.000000Z',
 'doctype': u'article',
 'doctype_facet_hier': [u'0/Article', u'1/Article/Journal Article'],
 'doi': [u'10.1088/0004-637X/815/2/133'],
 'eid': u'133',
 'email': [u'jhshinn@kasi.re.kr', u'-'],
 'first_author': u'Shinn, Jong-Ho',
 'first_author_facet_hier': [u'0/Shinn, J', u'1/Shinn, J/Shinn, Jong-Ho'],
 'first_author_norm': u'Shinn, J',
 'identifier': [u'1511.03789',
  u'10.1088/0004-637X/815/2/133',
  u'2015arXiv151103789S'],
 'issue': u'2',
 'keyword': [u'dust',
  u'extinction',
  u'galaxies: halos',
  u'galaxies: ISM',
  u'galaxies: spiral',
  u'galaxies: star formation',
  u'radiative transfer',
  u'Astrophysics - Astrophysics of Galaxies'],
 'keyword_facet': [u'dust',
  u'ism dust extinction',
  u'galaxies halos',
  u'galaxies intergalactic medium',
  u'galaxies spiral',
  u'galaxies star clusters',
  u'radiative transfer'],
 'keyword_norm': [u'dust',
  u'ism dust extinction',
  u'galaxies halos',
  u'galaxies intergalactic medium',
  u'galaxies spiral',
  u'galaxies star clusters',
  u'radiative transfer',
  u'-'],
 'keyword_schema': [u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'arXiv'],
 'links_data': [u'{"access": "", "instances": "7", "title": "", "type": "simbad", "url": "http://$SIMBAD$/simbo.pl?bibcode=2015ApJ...815..133S"}',
  u'{"access": "open", "instances": "", "title": "", "type": "pdf", "url": "http://stacks.iop.org/0004-637X/815/133/pdf"}',
  u'{"access": "", "instances": "6", "title": "", "type": "ned", "url": "http://ned.ipac.caltech.edu/cgi-bin/nph-objsearch?search_type=Search&refcode=2015ApJ...815..133S"}',
  u'{"access": "open", "instances": "", "title": "", "type": "preprint", "url": "http://arxiv.org/abs/1511.03789"}',
  u'{"access": "open", "instances": "", "title": "", "type": "electr", "url": "http://dx.doi.org/10.1088%2F0004-637X%2F815%2F2%2F133"}'],
 'orcid_pub': [u'0000-0001-7967-6473', u'0000-0001-9561-8134'],
 'page': [u'133'],
 'property': [u'OPENACCESS',
  u'REFEREED',
  u'EPRINT_OPENACCESS',
  u'PUB_OPENACCESS',
  u'ARTICLE'],
 'pub': u'The Astrophysical Journal',
 'pub_raw': u'The Astrophysical Journal, Volume 815, Issue 2, article id. 133, <NUMPAGES>14</NUMPAGES> pp. (2015).',
 'pubdate': u'2015-12-00',
 'pubnote': [u'33 pages, 7 figures, 5 tables, ApJ in press; doi:10.1088/0004-637X/815/2/133'],
 'read_count': 0,
 'reference': [u'1941ApJ....93...70H',
  u'1966ApJ...145..811P',
  u'1972A&A....18..253P',
  u'1972MNRAS.159..361C',
  u'1974A&A....35....7P',
  u'2015ApJ...813....7P',
  u'2015JKAS...48...57S',
  u'2015arXiv150907677B'],
 'title': [u'Ultraviolet Radiative Transfer Modeling of Nearby Galaxies with Extraplanar Dusts'],
 'volume': u'815',
 'year': u'2015'}