# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: augmentrecord.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import status_pb2 as status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='augmentrecord.proto',
  package='adsmsg',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x61ugmentrecord.proto\x12\x06\x61\x64smsg\x1a\x0cstatus.proto\"\x89\x01\n\x1f\x41ugmentAffiliationRequestRecord\x12\x0f\n\x07\x62ibcode\x18\x01 \x01(\t\x12\x1e\n\x06status\x18\x02 \x01(\x0e\x32\x0e.adsmsg.Status\x12\x13\n\x0b\x61\x66\x66iliation\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12\x10\n\x08sequence\x18\x05 \x01(\t\"\x8c\x01\n#AugmentAffiliationRequestRecordList\x12\x45\n\x14\x61\x66\x66iliation_requests\x18\x01 \x03(\x0b\x32\'.adsmsg.AugmentAffiliationRequestRecord\x12\x1e\n\x06status\x18\x02 \x01(\x0e\x32\x0e.adsmsg.Status\"\xcb\x01\n AugmentAffiliationResponseRecord\x12\x0f\n\x07\x62ibcode\x18\x01 \x01(\t\x12\x1e\n\x06status\x18\x02 \x01(\x0e\x32\x0e.adsmsg.Status\x12\x13\n\x0b\x61\x66\x66iliation\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12\x10\n\x08sequence\x18\x05 \x01(\t\x12\x1d\n\x15\x63\x61nonical_affiliation\x18\x06 \x01(\t\x12 \n\x18\x63\x61nonical_affiliation_id\x18\x07 \x01(\t\"\x8f\x01\n$AugmentAffiliationResponseRecordList\x12G\n\x15\x61\x66\x66iliation_responses\x18\x01 \x03(\x0b\x32(.adsmsg.AugmentAffiliationResponseRecord\x12\x1e\n\x06status\x18\x02 \x01(\x0e\x32\x0e.adsmsg.Statusb\x06proto3')
  ,
  dependencies=[status__pb2.DESCRIPTOR,])




_AUGMENTAFFILIATIONREQUESTRECORD = _descriptor.Descriptor(
  name='AugmentAffiliationRequestRecord',
  full_name='adsmsg.AugmentAffiliationRequestRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bibcode', full_name='adsmsg.AugmentAffiliationRequestRecord.bibcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='adsmsg.AugmentAffiliationRequestRecord.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='affiliation', full_name='adsmsg.AugmentAffiliationRequestRecord.affiliation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author', full_name='adsmsg.AugmentAffiliationRequestRecord.author', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='adsmsg.AugmentAffiliationRequestRecord.sequence', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=183,
)


_AUGMENTAFFILIATIONREQUESTRECORDLIST = _descriptor.Descriptor(
  name='AugmentAffiliationRequestRecordList',
  full_name='adsmsg.AugmentAffiliationRequestRecordList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='affiliation_requests', full_name='adsmsg.AugmentAffiliationRequestRecordList.affiliation_requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='adsmsg.AugmentAffiliationRequestRecordList.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=326,
)


_AUGMENTAFFILIATIONRESPONSERECORD = _descriptor.Descriptor(
  name='AugmentAffiliationResponseRecord',
  full_name='adsmsg.AugmentAffiliationResponseRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bibcode', full_name='adsmsg.AugmentAffiliationResponseRecord.bibcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='adsmsg.AugmentAffiliationResponseRecord.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='affiliation', full_name='adsmsg.AugmentAffiliationResponseRecord.affiliation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author', full_name='adsmsg.AugmentAffiliationResponseRecord.author', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='adsmsg.AugmentAffiliationResponseRecord.sequence', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canonical_affiliation', full_name='adsmsg.AugmentAffiliationResponseRecord.canonical_affiliation', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canonical_affiliation_id', full_name='adsmsg.AugmentAffiliationResponseRecord.canonical_affiliation_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=532,
)


_AUGMENTAFFILIATIONRESPONSERECORDLIST = _descriptor.Descriptor(
  name='AugmentAffiliationResponseRecordList',
  full_name='adsmsg.AugmentAffiliationResponseRecordList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='affiliation_responses', full_name='adsmsg.AugmentAffiliationResponseRecordList.affiliation_responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='adsmsg.AugmentAffiliationResponseRecordList.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=678,
)

_AUGMENTAFFILIATIONREQUESTRECORD.fields_by_name['status'].enum_type = status__pb2._STATUS
_AUGMENTAFFILIATIONREQUESTRECORDLIST.fields_by_name['affiliation_requests'].message_type = _AUGMENTAFFILIATIONREQUESTRECORD
_AUGMENTAFFILIATIONREQUESTRECORDLIST.fields_by_name['status'].enum_type = status__pb2._STATUS
_AUGMENTAFFILIATIONRESPONSERECORD.fields_by_name['status'].enum_type = status__pb2._STATUS
_AUGMENTAFFILIATIONRESPONSERECORDLIST.fields_by_name['affiliation_responses'].message_type = _AUGMENTAFFILIATIONRESPONSERECORD
_AUGMENTAFFILIATIONRESPONSERECORDLIST.fields_by_name['status'].enum_type = status__pb2._STATUS
DESCRIPTOR.message_types_by_name['AugmentAffiliationRequestRecord'] = _AUGMENTAFFILIATIONREQUESTRECORD
DESCRIPTOR.message_types_by_name['AugmentAffiliationRequestRecordList'] = _AUGMENTAFFILIATIONREQUESTRECORDLIST
DESCRIPTOR.message_types_by_name['AugmentAffiliationResponseRecord'] = _AUGMENTAFFILIATIONRESPONSERECORD
DESCRIPTOR.message_types_by_name['AugmentAffiliationResponseRecordList'] = _AUGMENTAFFILIATIONRESPONSERECORDLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AugmentAffiliationRequestRecord = _reflection.GeneratedProtocolMessageType('AugmentAffiliationRequestRecord', (_message.Message,), dict(
  DESCRIPTOR = _AUGMENTAFFILIATIONREQUESTRECORD,
  __module__ = 'augmentrecord_pb2'
  # @@protoc_insertion_point(class_scope:adsmsg.AugmentAffiliationRequestRecord)
  ))
_sym_db.RegisterMessage(AugmentAffiliationRequestRecord)

AugmentAffiliationRequestRecordList = _reflection.GeneratedProtocolMessageType('AugmentAffiliationRequestRecordList', (_message.Message,), dict(
  DESCRIPTOR = _AUGMENTAFFILIATIONREQUESTRECORDLIST,
  __module__ = 'augmentrecord_pb2'
  # @@protoc_insertion_point(class_scope:adsmsg.AugmentAffiliationRequestRecordList)
  ))
_sym_db.RegisterMessage(AugmentAffiliationRequestRecordList)

AugmentAffiliationResponseRecord = _reflection.GeneratedProtocolMessageType('AugmentAffiliationResponseRecord', (_message.Message,), dict(
  DESCRIPTOR = _AUGMENTAFFILIATIONRESPONSERECORD,
  __module__ = 'augmentrecord_pb2'
  # @@protoc_insertion_point(class_scope:adsmsg.AugmentAffiliationResponseRecord)
  ))
_sym_db.RegisterMessage(AugmentAffiliationResponseRecord)

AugmentAffiliationResponseRecordList = _reflection.GeneratedProtocolMessageType('AugmentAffiliationResponseRecordList', (_message.Message,), dict(
  DESCRIPTOR = _AUGMENTAFFILIATIONRESPONSERECORDLIST,
  __module__ = 'augmentrecord_pb2'
  # @@protoc_insertion_point(class_scope:adsmsg.AugmentAffiliationResponseRecordList)
  ))
_sym_db.RegisterMessage(AugmentAffiliationResponseRecordList)


# @@protoc_insertion_point(module_scope)
