# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: citation_changes_content_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='citation_changes_content_type.proto',
  package='adsmsg',
  syntax='proto3',
  serialized_pb=_b('\n#citation_changes_content_type.proto\x12\x06\x61\x64smsg*6\n\x19\x43itationChangeContentType\x12\x07\n\x03\x64oi\x10\x00\x12\x07\n\x03pid\x10\x01\x12\x07\n\x03url\x10\x02\x62\x06proto3')
)

_CITATIONCHANGECONTENTTYPE = _descriptor.EnumDescriptor(
  name='CitationChangeContentType',
  full_name='adsmsg.CitationChangeContentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='doi', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pid', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='url', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=47,
  serialized_end=101,
)
_sym_db.RegisterEnumDescriptor(_CITATIONCHANGECONTENTTYPE)

CitationChangeContentType = enum_type_wrapper.EnumTypeWrapper(_CITATIONCHANGECONTENTTYPE)
doi = 0
pid = 1
url = 2


DESCRIPTOR.enum_types_by_name['CitationChangeContentType'] = _CITATIONCHANGECONTENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
