# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nonbibrecord.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nonbibrecord.proto',
  package='adsmsg',
  syntax='proto2',
  serialized_pb=_b('\n\x12nonbibrecord.proto\x12\x06\x61\x64smsg\"\x9d\x02\n\x0cNonBibRecord\x12\x0f\n\x07\x62ibcode\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0f\n\x07\x61uthors\x18\x03 \x03(\t\x12\x10\n\x08refereed\x18\x04 \x01(\x08\x12\x16\n\x0esimbad_objects\x18\x05 \x03(\t\x12\x0e\n\x06grants\x18\x06 \x03(\t\x12\x11\n\tcitations\x18\x07 \x03(\t\x12\r\n\x05\x62oost\x18\x08 \x01(\x02\x12\x16\n\x0e\x63itation_count\x18\t \x01(\x05\x12\x12\n\nread_count\x18\n \x01(\x05\x12\x12\n\nnorm_cites\x18\x0b \x01(\x05\x12\x0f\n\x07readers\x18\x0c \x03(\x05\x12\x11\n\tdownloads\x18\r \x03(\x05\x12\r\n\x05reads\x18\x0e \x03(\x05\x12\x10\n\x08refernce\x18\x0f \x03(\t')
)




_NONBIBRECORD = _descriptor.Descriptor(
  name='NonBibRecord',
  full_name='adsmsg.NonBibRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bibcode', full_name='adsmsg.NonBibRecord.bibcode', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='adsmsg.NonBibRecord.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authors', full_name='adsmsg.NonBibRecord.authors', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refereed', full_name='adsmsg.NonBibRecord.refereed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='simbad_objects', full_name='adsmsg.NonBibRecord.simbad_objects', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grants', full_name='adsmsg.NonBibRecord.grants', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='citations', full_name='adsmsg.NonBibRecord.citations', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boost', full_name='adsmsg.NonBibRecord.boost', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='citation_count', full_name='adsmsg.NonBibRecord.citation_count', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_count', full_name='adsmsg.NonBibRecord.read_count', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='norm_cites', full_name='adsmsg.NonBibRecord.norm_cites', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='readers', full_name='adsmsg.NonBibRecord.readers', index=11,
      number=12, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='downloads', full_name='adsmsg.NonBibRecord.downloads', index=12,
      number=13, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reads', full_name='adsmsg.NonBibRecord.reads', index=13,
      number=14, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refernce', full_name='adsmsg.NonBibRecord.refernce', index=14,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=316,
)

DESCRIPTOR.message_types_by_name['NonBibRecord'] = _NONBIBRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NonBibRecord = _reflection.GeneratedProtocolMessageType('NonBibRecord', (_message.Message,), dict(
  DESCRIPTOR = _NONBIBRECORD,
  __module__ = 'nonbibrecord_pb2'
  # @@protoc_insertion_point(class_scope:adsmsg.NonBibRecord)
  ))
_sym_db.RegisterMessage(NonBibRecord)


# @@protoc_insertion_point(module_scope)
