# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nonbibrecord.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import status_pb2 as status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nonbibrecord.proto',
  package='adsmsg',
  syntax='proto3',
  serialized_pb=_b('\n\x12nonbibrecord.proto\x12\x06\x61\x64smsg\x1a\x0cstatus.proto\"\xd2\x03\n\x10NonBibSolrRecord\x12\x0f\n\x07\x62ibcode\x18\x01 \x01(\t\x12\x14\n\x0c\x61uthor_count\x18\x02 \x01(\x05\x12\x10\n\x08refereed\x18\x03 \x01(\x08\x12\x16\n\x0esimbad_objects\x18\x04 \x03(\t\x12\x0e\n\x06grants\x18\x05 \x03(\t\x12\x11\n\tcitations\x18\x06 \x03(\t\x12\r\n\x05\x62oost\x18\x07 \x01(\x02\x12\x16\n\x0e\x63itation_count\x18\x08 \x01(\x05\x12\x12\n\nread_count\x18\t \x01(\x05\x12\x0f\n\x07readers\x18\n \x03(\t\x12\x11\n\tdownloads\x18\x0b \x03(\x05\x12\r\n\x05reads\x18\x0c \x03(\x05\x12\x11\n\treference\x18\r \x03(\t\x12\x13\n\x0bned_objects\x18\x0e \x03(\t\x12\x30\n\x04\x64\x61ta\x18\x0f \x03(\x0b\x32\".adsmsg.NonBibSolrRecord.DataEntry\x12\x12\n\ndata_count\x18\x10 \x01(\x05\x12\x0f\n\x07\x65source\x18\x11 \x03(\t\x12\x10\n\x08property\x18\x12 \x03(\t\x12\x1e\n\x06status\x18\x13 \x01(\x0e\x32\x0e.adsmsg.Status\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"h\n\x14NonBibSolrRecordList\x12\x30\n\x0enonbib_records\x18\x01 \x03(\x0b\x32\x18.adsmsg.NonBibSolrRecord\x12\x1e\n\x06status\x18\x02 \x01(\x0e\x32\x0e.adsmsg.Statusb\x06proto3')
  ,
  dependencies=[status__pb2.DESCRIPTOR,])




_NONBIBSOLRRECORD_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='adsmsg.NonBibSolrRecord.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='adsmsg.NonBibSolrRecord.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='adsmsg.NonBibSolrRecord.DataEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=511,
)

_NONBIBSOLRRECORD = _descriptor.Descriptor(
  name='NonBibSolrRecord',
  full_name='adsmsg.NonBibSolrRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bibcode', full_name='adsmsg.NonBibSolrRecord.bibcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author_count', full_name='adsmsg.NonBibSolrRecord.author_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refereed', full_name='adsmsg.NonBibSolrRecord.refereed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='simbad_objects', full_name='adsmsg.NonBibSolrRecord.simbad_objects', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grants', full_name='adsmsg.NonBibSolrRecord.grants', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='citations', full_name='adsmsg.NonBibSolrRecord.citations', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boost', full_name='adsmsg.NonBibSolrRecord.boost', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='citation_count', full_name='adsmsg.NonBibSolrRecord.citation_count', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_count', full_name='adsmsg.NonBibSolrRecord.read_count', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='readers', full_name='adsmsg.NonBibSolrRecord.readers', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='downloads', full_name='adsmsg.NonBibSolrRecord.downloads', index=10,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reads', full_name='adsmsg.NonBibSolrRecord.reads', index=11,
      number=12, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reference', full_name='adsmsg.NonBibSolrRecord.reference', index=12,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ned_objects', full_name='adsmsg.NonBibSolrRecord.ned_objects', index=13,
      number=14, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='adsmsg.NonBibSolrRecord.data', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_count', full_name='adsmsg.NonBibSolrRecord.data_count', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='esource', full_name='adsmsg.NonBibSolrRecord.esource', index=16,
      number=17, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='property', full_name='adsmsg.NonBibSolrRecord.property', index=17,
      number=18, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='adsmsg.NonBibSolrRecord.status', index=18,
      number=19, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NONBIBSOLRRECORD_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=511,
)


_NONBIBSOLRRECORDLIST = _descriptor.Descriptor(
  name='NonBibSolrRecordList',
  full_name='adsmsg.NonBibSolrRecordList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonbib_records', full_name='adsmsg.NonBibSolrRecordList.nonbib_records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='adsmsg.NonBibSolrRecordList.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=617,
)

_NONBIBSOLRRECORD_DATAENTRY.containing_type = _NONBIBSOLRRECORD
_NONBIBSOLRRECORD.fields_by_name['data'].message_type = _NONBIBSOLRRECORD_DATAENTRY
_NONBIBSOLRRECORD.fields_by_name['status'].enum_type = status__pb2._STATUS
_NONBIBSOLRRECORDLIST.fields_by_name['nonbib_records'].message_type = _NONBIBSOLRRECORD
_NONBIBSOLRRECORDLIST.fields_by_name['status'].enum_type = status__pb2._STATUS
DESCRIPTOR.message_types_by_name['NonBibSolrRecord'] = _NONBIBSOLRRECORD
DESCRIPTOR.message_types_by_name['NonBibSolrRecordList'] = _NONBIBSOLRRECORDLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NonBibSolrRecord = _reflection.GeneratedProtocolMessageType('NonBibSolrRecord', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _NONBIBSOLRRECORD_DATAENTRY,
    __module__ = 'nonbibrecord_pb2'
    # @@protoc_insertion_point(class_scope:adsmsg.NonBibSolrRecord.DataEntry)
    ))
  ,
  DESCRIPTOR = _NONBIBSOLRRECORD,
  __module__ = 'nonbibrecord_pb2'
  # @@protoc_insertion_point(class_scope:adsmsg.NonBibSolrRecord)
  ))
_sym_db.RegisterMessage(NonBibSolrRecord)
_sym_db.RegisterMessage(NonBibSolrRecord.DataEntry)

NonBibSolrRecordList = _reflection.GeneratedProtocolMessageType('NonBibSolrRecordList', (_message.Message,), dict(
  DESCRIPTOR = _NONBIBSOLRRECORDLIST,
  __module__ = 'nonbibrecord_pb2'
  # @@protoc_insertion_point(class_scope:adsmsg.NonBibSolrRecordList)
  ))
_sym_db.RegisterMessage(NonBibSolrRecordList)


_NONBIBSOLRRECORD_DATAENTRY.has_options = True
_NONBIBSOLRRECORD_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
