# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orcid_claims.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import status_pb2 as status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='orcid_claims.proto',
  package='adsmsg',
  syntax='proto3',
  serialized_pb=_b('\n\x12orcid_claims.proto\x12\x06\x61\x64smsg\x1a\x0cstatus.proto\"u\n\x0bOrcidClaims\x12\x0f\n\x07\x62ibcode\x18\x01 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x02 \x03(\t\x12\x10\n\x08verified\x18\x03 \x03(\t\x12\x12\n\nunverified\x18\x04 \x03(\t\x12\x1e\n\x06status\x18\x05 \x01(\x0e\x32\x0e.adsmsg.Statusb\x06proto3')
  ,
  dependencies=[status__pb2.DESCRIPTOR,])




_ORCIDCLAIMS = _descriptor.Descriptor(
  name='OrcidClaims',
  full_name='adsmsg.OrcidClaims',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bibcode', full_name='adsmsg.OrcidClaims.bibcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authors', full_name='adsmsg.OrcidClaims.authors', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verified', full_name='adsmsg.OrcidClaims.verified', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unverified', full_name='adsmsg.OrcidClaims.unverified', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='adsmsg.OrcidClaims.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=161,
)

_ORCIDCLAIMS.fields_by_name['status'].enum_type = status__pb2._STATUS
DESCRIPTOR.message_types_by_name['OrcidClaims'] = _ORCIDCLAIMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrcidClaims = _reflection.GeneratedProtocolMessageType('OrcidClaims', (_message.Message,), dict(
  DESCRIPTOR = _ORCIDCLAIMS,
  __module__ = 'orcid_claims_pb2'
  # @@protoc_insertion_point(class_scope:adsmsg.OrcidClaims)
  ))
_sym_db.RegisterMessage(OrcidClaims)


# @@protoc_insertion_point(module_scope)
