# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: turbobee.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import status_pb2 as status__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='turbobee.proto',
  package='adsmsg',
  syntax='proto3',
  serialized_pb=_b('\n\x0eturbobee.proto\x12\x06\x61\x64smsg\x1a\x0cstatus.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x03\n\x0bTurboBeeMsg\x12\x0b\n\x03qid\x18\x01 \x01(\t\x12\x1e\n\x06status\x18\x02 \x01(\x0e\x32\x0e.adsmsg.Status\x12\x0e\n\x06target\x18\x03 \x01(\t\x12+\n\x07\x63reated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x65xpires\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65ol\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05owner\x18\x08 \x01(\x05\x12(\n\x05\x63type\x18\t \x01(\x0e\x32\x19.adsmsg.TurboBeeMsg.CType\x12\r\n\x05value\x18\n \x01(\x0c\"G\n\x05\x43Type\x12\x0b\n\x07unknown\x10\x00\x12\x08\n\x04html\x10\x01\x12\x08\n\x04text\x10\x02\x12\x08\n\x04json\x10\x03\x12\n\n\x06\x62inary\x10\x04\x12\x07\n\x03png\x10\x05\x62\x06proto3')
  ,
  dependencies=[status__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_TURBOBEEMSG_CTYPE = _descriptor.EnumDescriptor(
  name='CType',
  full_name='adsmsg.TurboBeeMsg.CType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='unknown', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='html', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='text', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='json', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='binary', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='png', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=398,
  serialized_end=469,
)
_sym_db.RegisterEnumDescriptor(_TURBOBEEMSG_CTYPE)


_TURBOBEEMSG = _descriptor.Descriptor(
  name='TurboBeeMsg',
  full_name='adsmsg.TurboBeeMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qid', full_name='adsmsg.TurboBeeMsg.qid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='adsmsg.TurboBeeMsg.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='adsmsg.TurboBeeMsg.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created', full_name='adsmsg.TurboBeeMsg.created', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updated', full_name='adsmsg.TurboBeeMsg.updated', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expires', full_name='adsmsg.TurboBeeMsg.expires', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eol', full_name='adsmsg.TurboBeeMsg.eol', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='adsmsg.TurboBeeMsg.owner', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ctype', full_name='adsmsg.TurboBeeMsg.ctype', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='adsmsg.TurboBeeMsg.value', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TURBOBEEMSG_CTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=469,
)

_TURBOBEEMSG.fields_by_name['status'].enum_type = status__pb2._STATUS
_TURBOBEEMSG.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TURBOBEEMSG.fields_by_name['updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TURBOBEEMSG.fields_by_name['expires'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TURBOBEEMSG.fields_by_name['eol'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TURBOBEEMSG.fields_by_name['ctype'].enum_type = _TURBOBEEMSG_CTYPE
_TURBOBEEMSG_CTYPE.containing_type = _TURBOBEEMSG
DESCRIPTOR.message_types_by_name['TurboBeeMsg'] = _TURBOBEEMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TurboBeeMsg = _reflection.GeneratedProtocolMessageType('TurboBeeMsg', (_message.Message,), dict(
  DESCRIPTOR = _TURBOBEEMSG,
  __module__ = 'turbobee_pb2'
  # @@protoc_insertion_point(class_scope:adsmsg.TurboBeeMsg)
  ))
_sym_db.RegisterMessage(TurboBeeMsg)


# @@protoc_insertion_point(module_scope)
